version: '3'
services:
  wordpress_app:
    build: ./wordpress_app
    ports:
      - "5001:80"
    volumes:
      - ./wordpress_app/wp-content:/var/www/html/wp-content
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: user
      MYSQL_PASSWORD: password

  static_html_app:
    build: ./static_html_app
    ports:
      - "5002:80"

  flask_app:
    build: ./flask_app
    ports:
      - "5003:5000"

  express_app:
    build: ./express_app
    ports:
      - "5004:3000"

  react_app:
    build: ./react_app
    ports:
      - "5005:3000"
